/* src/App.svelte generated by Svelte v3.23.2 */
import {
	SvelteComponent,
	attr,
	create_component,
	destroy_component,
	detach,
	element,
	init,
	insert,
	mount_component,
	noop,
	safe_not_equal,
	transition_in,
	transition_out
} from "https://jcc2303.github.io/sign-language/web_modules/svelte/internal.js";

import "./main.css.proxy.js";
import Handpose from "./Handpose.js";

function create_fragment(ctx) {
	let div;
	let handpose;
	let current;
	handpose = new Handpose({});

	return {
		c() {
			div = element("div");
			create_component(handpose.$$.fragment);
			attr(div, "class", "bg-yellow-300");
		},
		m(target, anchor) {
			insert(target, div, anchor);
			mount_component(handpose, div, null);
			current = true;
		},
		p: noop,
		i(local) {
			if (current) return;
			transition_in(handpose.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(handpose.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(div);
			destroy_component(handpose);
		}
	};
}

class App extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default App;